name: ecshop
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
#----packages----#
dependencies:
  flutter:
    sdk: flutter

#-----icons-----#
  cupertino_icons: ^1.0.2
#----design clipper----#
  flutter_custom_clippers: ^2.1.0
#------dropdown option------#
  dropdown_button2: ^2.3.9
#---image all attributes----#
  image_picker: ^1.0.4
  image: ^4.1.3
  image_cropper: ^5.0.0
  custom_image_crop: ^0.0.12
#----dart essential----#
  path: ^1.8.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  smooth_page_indicator: ^1.1.0
#---flutter path provide----#
  path_provider: ^2.1.1
  flutter_native_splash: ^2.3.4
  auto_route: ^7.8.4
#----State management-----#
  iconsax: ^0.0.8
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #----------For native splash screen------------#
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logo/blogo.jpeg
  image_dark: assets/logo/blogo.jpeg
  android_12:
    image: assets/logo/blogo.jpeg
    icon_background_color: "#FFFFFF"
    image_dark: assets/logo/blogo.jpeg
    icon_background_color_dark: "#272727"
  ios: true
  web: false
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/on_boarding_images/

  #-----local fonts -----#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
